on: gollum
name: New resources
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: A new resource has been added to the wiki page!
          SLACK_USERNAME: Book Worm
          SLACK_ICON_EMOJI: ":bug:"
          SLACK_MESSAGE: "You can view the new resource on the [QTMA shared-resources repository](https://github.com/QueensTechMediaAssociation/shared-resources/wiki)"
          MSG_MINIMAL: true
          SLACK_FOOTER: ""
